server:
  port : 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ptk?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ptk
    password: 0941
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platfrom: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update